config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('tournament/', include('tournament.urls'))
]


admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Естественно Научный Турнир"

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name="password_reset"),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name="password_reset_confirm"),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    training_organization = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="",
                               widget=forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label="",
                               widget=forms.PasswordInput(attrs={'class': 'css_input', 'placeholder': 'Пароль'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'Имя пользователя'})
    )
    email = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'E-mail'})
    )
    training_organization = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'Название ОО'})
    )
    password1 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'class': 'css_input', 'placeholder': 'Пароль'})
    )
    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'class': 'css_input', 'placeholder': 'Повтор пароля'})
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'training_organization', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='', widget=forms.TextInput(attrs={'class': 'css_input'}))
    email = forms.CharField(disabled=True, label='', widget=forms.TextInput(attrs={'class': 'css_input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'training_organization', 'first_name', 'last_name']
        labels = {
            'training_organization': '',
            'first_name': '',
            'last_name': '',
        }
        widgets = {
            'training_organization': forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'Название ОО'}),
            'first_name': forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'css_input', 'placeholder': 'Фамилия'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="",
                                   widget=forms.PasswordInput(attrs={'class': 'css_input', 'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(label="",
                                    widget=forms.PasswordInput(attrs={'class': 'css_input', 'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(label="",
                                    widget=forms.PasswordInput(attrs={'class': 'css_input', 'placeholder': 'Повторите пароль'}))

users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="features">
    <h1>Авторизация</h1>

    <form class="form__features" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="button_register">Войти</button></p>
    </form>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <h1>Пароль успешно изменен</h1>
    <p>Вы успешно именили пароль.<a href="{% url 'users:profile' %}">Вернуться в профиль</a></p>
</div>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="features">
    <form class="form__features" method="post">
        {% csrf_token %}
        <h1>Смена пароля</h1>
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="button_register">Изменить пароль</button></p>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content%}
<div class="features">
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
    <a href="{% url 'users:login' %}">входа в систему</a></p>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <form class="form__features" method="post">
        {% csrf_token %}
        <h1>Новый пароль</h1>
        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="button_register">Сохранить</button></p>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="features">
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}

{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}


{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <form class="form__features" method="post">
        {% csrf_token %}
        <h1>Восстановление пароля</h1>
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="button_register">Сбросить по E-mail</button></p>
    </form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <h1>Профиль</h1>
    <form class="form__features" method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_fields_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button class="button_register" type="submit">Сохранить</button> </p>
    </form>
    <hr>
    <p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <form class="form__features" method="post">
        {% csrf_token %}
        <h1>Регистрация</h1>
        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="button_register">Регистрация</button></p>
    </form>
</div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <h1>Добро пожаловать!</h1>

    <p>Вы успешно заригистрировались на сайте! Для входа в систему необходимо авторизоваться по
        <a href="{% url 'users:login' %}">ссылке</a>
    </p>
</div>
{% endblock %}